import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import Navbar from '@/components/shared/navigation';
import { Toaster } from 'sonner';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gister',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={rubik.className}>
          <Navbar />
          <main className='mx-auto max-w-screen-md min-h-[80vh] px-4 md:px-5 py-7 md:py-10'>
            {children}
          </main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
